### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by cocoliliace** [BootcampToProd/spring-boot-read-request-body-multiple-times#1]
Hi thank you for the great explanation and the sample code!

The custom request and input stream classes do exactly what I want to achieve and I can't think of a different way of implementing them so I'm thinking of using the code with minimal changes.

Can you please add a license to the code so I know how to legally use it in my project, if I may use it at all? It's for work so I need to make sure I'm in the clear before using it :)

Here are some good sources for choosing a license:
- https://choosealicense.com/
- https://man.sr.ht/license.md

**Comment by BootcampToProd** [comment]
Hello,
Thank you for your kind words. I am glad you found the content useful. You
can use the source code.

**Comment by cocoliliace** [comment]
Thank you! Take care :)
